name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t gayatrimishraa/typing-test .

    - name: Push Docker image to Docker Hub
      run: docker push gayatrimishraa/typing-test

    - name: Run system test
      run: |
        chmod +x test_container.sh
        ./test_container.sh
<<<<<<< HEAD

=======
>>>>>>> a36742b8ffd01a403ac7ea1abef83bd36fb57c92
